version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=maxim
      - DB_PASSWORD=admin
      - DB_NAME=user_database
    # Якщо потрібно – можна примонтувати том для розробки:
    # volumes:
    #   - .:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_database
      MYSQL_USER: maxim
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
